OPM/opm-upscaling

CMakeLists.txt
TestUpscalingBinaries.cmake
tests/runtest.sh

- use common test macro
- use a test driver instead of test dependencies
@andlaus for review. requires https://github.com/OPM/opm-cmake/pull/18

Use opm_add_test_macro

---

opm/upscaling/ParserAdditions.hpp

This is fixes a minor fallout after: https://github.com/OPM/opm-parser/pull/489

Using ParserKeyword constructor.

---

examples/upscale_cond.cpp
examples/upscale_relperm.cpp
examples/upscale_relpermvisc.cpp

thanks to @bska for pointing it out.

changed: replace C99-style VLAs with std::vector

---

examples/cpregularize.cpp
examples/grdecldips.cpp
examples/upscale_avg.cpp
examples/upscale_cap.cpp
examples/upscale_cond.cpp
examples/upscale_perm.cpp
examples/upscale_relperm.cpp
examples/upscale_relpermvisc.cpp
examples/upscale_steadystate_implicit.cpp
opm/elasticity/elasticity_upscale_impl.hpp

Followup to: https://github.com/OPM/opm-parser/pull/527

Added ParseMode argument

---

benchmarks/upscale_relperm_benchmark.cpp
examples/upscale_relperm.cpp
opm/upscaling/RelPermUtils.cpp

Forgot to test my refactoring with MPI - no excuse.
Also fixes a build issue in the benchmark due to changes in opm-parser.

Fix mpi build

---

redhat/opm-upscaling.spec

update redhat packaging

---

examples/upscale_avg.cpp
examples/upscale_cap.cpp
examples/upscale_cond.cpp
examples/upscale_relperm.cpp
opm/elasticity/elasticity_upscale_impl.hpp

Adopting to opm-parser PR#661, add previously missing includes.
http://github.com/OPM/opm-parser/pull/661

Improve includes from opm-parser

---

examples/cpchop.cpp
examples/grdecldips.cpp
examples/upscale_avg.cpp
examples/upscale_cap.cpp
examples/upscale_cond.cpp
examples/upscale_relperm.cpp
examples/upscale_relpermvisc.cpp
examples/upscale_steadystate_implicit.cpp
opm/elasticity/elasticity_upscale_impl.hpp
opm/upscaling/RelPermUtils.cpp

opm-parser#677 changes the return types for the Deck family of classes.
This patch fixes all broken code from that patch set.
https://github.com/OPM/opm-parser/pull/677

Change Deck access methods/types to references

---

opm/elasticity/elasticity_upscale_impl.hpp

Depend on https://github.com/OPM/opm-porsol/pull/144

rename ParseMode as ParseContext.

---

benchmarks/upscale_relperm_benchmark.cpp
examples/cpregularize.cpp
examples/grdecldips.cpp
examples/upscale_avg.cpp
examples/upscale_cap.cpp
examples/upscale_cond.cpp
examples/upscale_perm.cpp
examples/upscale_relperm.cpp
examples/upscale_relpermvisc.cpp
examples/upscale_steadystate_implicit.cpp

Example programs forgotten in #171.

Chase ParseMode -> ParseContext Renaming in Examples

---

examples/cpchop.cpp
examples/cpchop_depthtrend.cpp
examples/cpregularize.cpp
examples/exp_variogram.cpp
examples/grdecldips.cpp
examples/known_answer_test.cpp
examples/mimetic_aniso_solver_test.cpp
examples/upscale_avg.cpp
opm/porsol/common/ReservoirPropertyCommon_impl.hpp
opm/porsol/common/Rock_impl.hpp
opm/upscaling/SteadyStateUpscalerImplicit_impl.hpp

Fix compilation of opm-upscaling.

---

jenkins/README.md
jenkins/build-opm-upscaling.sh
jenkins/build-pr.sh
jenkins/build.sh

This is the build scripts for this module, ref OPM/opm-common#102 and OPM/opm-parser#743

Jenkins reboot

---

opm/porsol/blackoil/co2fluid/BlackoilCo2PVT.hpp

@andlaus please confirm and merge if correct.

Fix build after opm material change

---

jenkins/build-opm-upscaling.sh
jenkins/build-pr.sh
jenkins/build.sh

changes done related to downstream triggers made
it easier to build upstreams as well
depends on https://github.com/OPM/opm-common/pull/111

simplify jenkins build scripts a little

---

benchmarks/upscale_relperm_benchmark.cpp
jenkins/build-opm-upscaling.sh

Fix build of benchmark after parser changes.
Enable build of benchmark on jenkins
@alfbr

Fix benchmark build

---

CMakeLists_files.cmake
examples/known_answer_test.cpp
examples/mimetic_periodic_test.cpp
examples/upscale_elasticity.cpp
opm/porsol/blackoil/BlackoilSimulator.hpp
opm/porsol/common/setupGridAndProps.hpp
opm/upscaling/initCPGrid.cpp
opm/upscaling/initCPGrid.hpp

This is a followup to: https://github.com/OPM/opm-grid/pull/216/

Changed grid initialisation.

---

.travis.yml
travis/build-and-test-opm-upscaling.sh
travis/build-opm-upscaling.sh

add travis setup

---

opm/upscaling/SteadyStateUpscalerImplicit_impl.hpp

Breaking opm-core dependency in opm-output; new summary implementation

---

jenkins/build-opm-upscaling.sh
jenkins/build-pr.sh
jenkins/build.sh

Depends on https://github.com/OPM/opm-common/pull/168

simplify jenkins build scripts after ert reorganization

---

examples/upscale_elasticity.cpp
opm/porsol/blackoil/BlackoilSimulator.hpp
opm/porsol/common/setupGridAndProps.hpp
opm/upscaling/initCPGrid.cpp

See: https://github.com/OPM/opm-simulators/pull/804

shared_ptr<EclipseGrid> -> const EclipseGrid&

---

redhat/opm-upscaling.spec

update redhat6 packaging

---

opm/upscaling/SteadyStateUpscalerImplicit_impl.hpp

Followup to: https://github.com/OPM/opm-output/pull/101

Adapt to changes in output-interface.

---

benchmarks/upscale_relperm_benchmark.cpp

adapt to the move of Unused.hpp from opm-material to opm-common

---

opm/porsol/blackoil/co2fluid/BlackoilCo2PVT.hpp

Exposed by upstream header changes.

Add missing include directive.

---

CMakeLists_files.cmake
opm/core/utility/Average.hpp

Upstream: https://github.com/OPM/opm-core/pull/1194

Import Average.hpp from opm-core

---

CMakeLists_files.cmake

Fix Pathname to "Average.hpp"

---

CMakeLists.txt
dune.module
opm-upscaling-prereqs.cmake

Upstream: https://github.com/OPM/opm-common/pull/304

changed: put prereqs in module itself

---

opm/porsol/common/ImplicitTransportDefs.hpp

Just a small step, but makes it a little easier to (re)move opm-core things.

Removing unused code, eliminating unnecessary deps.

---

CMakeLists_files.cmake
opm/core/transport/implicit/CSRMatrixBlockAssembler.hpp
opm/core/transport/implicit/CSRMatrixUmfpackSolver.hpp
opm/core/transport/implicit/ImplicitAssembly.hpp
opm/core/transport/implicit/ImplicitTransport.hpp
opm/core/transport/implicit/JacobianSystem.hpp
opm/core/transport/implicit/NormSupport.hpp
opm/core/transport/implicit/SimpleFluid2pWrappingProps.hpp
opm/core/transport/implicit/SimpleFluid2pWrappingProps_impl.hpp
opm/core/transport/implicit/SinglePointUpwindTwoPhase.hpp
opm/core/transport/implicit/TransportSolverTwophaseImplicit.cpp
opm/core/transport/implicit/TransportSolverTwophaseImplicit.hpp
opm/core/transport/implicit/transport_source.c
opm/core/transport/implicit/transport_source.h

Note the history isn't entirely clean but it would take a lot of surgery to clean it up entirely due to the the early mess in the opm-core repo so this is a balance between clean history and effort.

Import implicit transport

---

debian/control
dune.module
jenkins/build.sh
opm-upscaling-prereqs.cmake
redhat/opm-upscaling.spec

also update debian/redhat packaging

remove opm-core from upstream and prerequisite lists

---

examples/cpchop.cpp
examples/grdecldips.cpp
examples/known_answer_test.cpp
examples/mimetic_aniso_solver_test.cpp
examples/mimetic_periodic_test.cpp
examples/mimetic_solver_test.cpp
examples/upscale_cap.cpp
examples/upscale_cond.cpp
examples/upscale_elasticity.cpp
examples/upscale_relpermvisc.cpp
examples/upscale_steadystate_implicit.cpp
opm/elasticity/elasticity_upscale.hpp
opm/porsol/common/ImplicitTransportDefs.hpp
opm/porsol/common/RockAnisotropicRelperm.hpp
opm/porsol/common/RockJfunc.hpp
opm/porsol/common/SimulatorBase.hpp
opm/porsol/common/setupBoundaryConditions.hpp
opm/porsol/common/setupGridAndProps.hpp
opm/porsol/euler/EulerUpstream.hpp
opm/porsol/euler/EulerUpstreamImplicit.hpp
opm/porsol/euler/EulerUpstreamResidual.hpp
opm/porsol/euler/ImplicitCapillarity.hpp
opm/porsol/euler/ImplicitCapillarity_impl.hpp
opm/upscaling/RelPermUtils.hpp
opm/upscaling/UpscalerBase.hpp
opm/upscaling/initCPGrid.cpp
opm/upscaling/initCPGrid.hpp

Downstream of https://github.com/OPM/opm-common/pull/326

Relocate files in common

---

examples/known_answer_test.cpp
examples/mimetic_aniso_solver_test.cpp
examples/mimetic_periodic_test.cpp
examples/mimetic_solver_test.cpp
examples/upscale_elasticity.cpp
opm/elasticity/elasticity_preconditioners.hpp
opm/elasticity/elasticity_upscale.hpp
opm/elasticity/meshcolorizer.cpp
opm/porsol/common/GridInterfaceEuler.hpp
opm/porsol/common/ImplicitTransportDefs.cpp
opm/porsol/common/ImplicitTransportDefs.hpp
opm/porsol/common/SimulatorBase.hpp
opm/porsol/common/Wells.hpp
opm/porsol/common/setupGridAndProps.hpp
opm/porsol/euler/EulerUpstreamImplicit.hpp
opm/porsol/euler/EulerUpstreamImplicit_impl.hpp
opm/porsol/euler/EulerUpstreamResidual_impl.hpp
opm/porsol/euler/EulerUpstream_impl.hpp
opm/porsol/euler/ImplicitCapillarity_impl.hpp
opm/porsol/mimetic/IncompFlowSolverHybrid.hpp
opm/porsol/mimetic/MimeticIPAnisoRelpermEvaluator.hpp
opm/porsol/mimetic/MimeticIPEvaluator.hpp
opm/upscaling/SteadyStateUpscalerImplicit.hpp
opm/upscaling/SteadyStateUpscalerManager.hpp
opm/upscaling/SteadyStateUpscalerManagerImplicit.hpp
opm/upscaling/UpscalerBase.hpp
opm/upscaling/initCPGrid.cpp
opm/upscaling/initCPGrid.hpp

Adapt to moved headers in opm-grid.

---

dune.module
jenkins/build.sh
opm-upscaling-prereqs.cmake

Downstream of https://github.com/OPM/opm-common/pull/341

adjustments for eclipse support in opm-common

---

jenkins/build.sh

setup-opm-data -> setup-opm-tests

---

benchmarks/upscale_relperm_benchmark.cpp
examples/cpregularize.cpp
examples/mimetic_aniso_solver_test.cpp
examples/upscale_elasticity.cpp
opm/elasticity/elasticity_upscale_impl.hpp
opm/porsol/common/setupGridAndProps.hpp
opm/upscaling/CornerpointChopper.hpp
opm/upscaling/RelPermUtils.hpp
opm/upscaling/initCPGrid.cpp
tests/common/test_gravitypressure.cpp

Downstream of: https://github.com/OPM/opm-common/pull/602

Remove ParseContext argument

---

benchmarks/upscale_relperm_benchmark.cpp
examples/cpchop.cpp
examples/cpregularize.cpp
examples/upscale_cap.cpp
examples/upscale_cond.cpp
opm/core/transport/implicit/transport_source.c
opm/elasticity/boundarygrid.hh
opm/elasticity/material.cpp
opm/elasticity/mortar_evaluator.hpp
opm/elasticity/mortar_schur.hpp
opm/elasticity/mortar_schur_precond.hpp
opm/elasticity/uzawa_solver.hpp
opm/porsol/euler/EulerUpstreamResidual_impl.hpp
opm/porsol/mimetic/IncompFlowSolverHybrid.hpp
opm/upscaling/RelPermUtils.cpp
tests/compareUpscaling.cpp

Quell static analyzer and additional clang warnings.

Various janitoring

---

opm/upscaling/CornerpointChopper.hpp

Downstream of: https://github.com/OPM/opm-common/pull/1001

Change in DeckKeyword api - add ParserKeyword *

---

opm/upscaling/RelPermUtils.cpp

To be merged with OPM/opm-common#1009.

Update for upstream API change.

---

opm/upscaling/CornerpointChopper.hpp

Downstream of: https://github.com/OPM/opm-common/pull/1005

Use ParserKeyword& instead of ParserKeyword*

---

opm/upscaling/writeECLData.cpp

This commit switches the implementation of function
```
Opm::writeECLData()
```
to use the [`Opm::EclIO::OutputStream::Restart`](https://github.com/OPM/opm-common/blob/3d3f315b0accda6890ac41a8283bb3c26b334fc6/opm/io/eclipse/OutputStream.hpp#L131-L132) class from opm-common.  This, in turn, means that opm-upscaling no longer depends on LibECL.

Reimplement 'writeECLData' Without LibECL

---

opm/upscaling/CornerpointChopper.hpp

Followup to: https://github.com/OPM/opm-common/pull/1021

Use dimenisons from Parser

---

opm/upscaling/writeECLData.cpp

Downstream of: https://github.com/OPM/opm-common/pull/1450

Update INTEHEAD initialization

---

opm/porsol/common/ReservoirPropertyCapillaryAnisotropicRelperm_impl.hpp

changed: use standard lambda instead of boost::lambda

---

opm/porsol/common/GridInterfaceEuler.hpp
opm/porsol/mimetic/IncompFlowSolverHybrid.hpp

changed: use std::unique_ptr instead of boost::scoped_ptr

---

opm/porsol/euler/EulerUpstream.hpp
opm/porsol/euler/EulerUpstreamImplicit.hpp
opm/porsol/euler/EulerUpstreamResidual.hpp
opm/porsol/mimetic/IncompFlowSolverHybrid.hpp

changed: use unordered_map from stl instead of boost

---

opm/porsol/common/Matrix.hpp
opm/porsol/euler/MatchSaturatedVolumeFunctor.hpp
opm/porsol/mimetic/IncompFlowSolverHybrid.hpp
opm/porsol/mimetic/MimeticIPAnisoRelpermEvaluator.hpp
opm/porsol/mimetic/MimeticIPEvaluator.hpp

changed: use lambdas instead of boost::bind

---

opm-upscaling-prereqs.cmake

Downstream of https://github.com/OPM/opm-common/pull/1456

remove usage of CXX11Features module

---

opm-upscaling-prereqs.cmake
opm/porsol/common/setupGridAndProps.hpp

Downstream of https://github.com/OPM/opm-common/pull/1461

changed: "use" std::filesystem instead of boost::filesystem

---

examples/cpchop.cpp
examples/cpchop_depthtrend.cpp
examples/exp_variogram.cpp

changed: use std::random instead of boost::random

---

opm/porsol/mimetic/IncompFlowSolverHybrid.hpp

Do not copy large vectors into an inner-loop lambda.

---

CMakeLists.txt

downstream of OPM/opm-common#1675

Refactor policy settings (Needed by OPM/opm-common#1675)

---

opm/upscaling/writeECLData.cpp

Supply All Well Table Dimensions for INTEHEAD

---

examples/upscale_elasticity.cpp
opm/porsol/common/setupGridAndProps.hpp
opm/upscaling/initCPGrid.cpp

updating the interface of processEclipseFormat

---

opm/porsol/common/setupGridAndProps.hpp
opm/upscaling/initCPGrid.cpp

downstream of OPM/opm-grid#539

Force opm-grid to pinch.

---

examples/mimetic_aniso_solver_test.cpp

Downstream of OPM/opm-grid#538

Cater for removed z_tolerance param of CpGrid::processEclipseFormat

---

examples/upscale_steadystate_implicit.cpp
opm/porsol/mimetic/IncompFlowSolverHybrid.hpp
opm/upscaling/SteadyStateUpscalerManagerImplicit.hpp

Downstream of https://github.com/OPM/opm-grid/pull/541

adjust to iterator_range from opm-grid

---

benchmarks/upscale_relperm_benchmark.cpp
examples/cpchop.cpp
examples/grdecldips.cpp
examples/mimetic_aniso_solver_test.cpp
examples/upscale_avg.cpp
examples/upscale_cap.cpp
examples/upscale_cond.cpp
examples/upscale_relpermvisc.cpp
examples/upscale_steadystate_implicit.cpp
opm/elasticity/elasticity_upscale_impl.hpp
opm/porsol/common/ReservoirPropertyCommon_impl.hpp
opm/porsol/common/Rock_impl.hpp
opm/upscaling/CornerpointChopper.hpp
opm/upscaling/RelPermUtils.cpp

Downstream of: OPM/opm-common#2856

Update deck access api

---

doc/man1/cpchop.1

Hopefully all options documented in manpage now.
Closes #356

Updated man page for cpchop

---

examples/upscale_relpermvisc.cpp
opm/elasticity/logutils.hpp
opm/porsol/common/GridInterfaceEuler.hpp
opm/porsol/euler/EulerUpstreamImplicit_impl.hpp
opm/porsol/mimetic/IncompFlowSolverHybrid.hpp

- remove unused variables
- change an if to avoid warning with clang and no openmp

Some janitoring

---

opm/porsol/common/GridInterfaceEuler.hpp

Downstream of OPM/opm-grid#587

Adapt to removed EntityPointer (in DUNE 2.9)

---

jenkins/build.sh

remove opm-material from upstreams
Downstream of https://github.com/OPM/opm-common/pull/3234

adjust jenkins script

---

examples/cpchop.cpp
examples/upscale_steadystate_implicit.cpp
opm/elasticity/mpc.cpp
opm/elasticity/mpc.hh
opm/porsol/common/ReservoirPropertyCommon_impl.hpp
opm/porsol/common/RockAnisotropicRelperm.hpp
opm/porsol/common/RockJfunc.hpp
opm/porsol/common/SimulatorBase.hpp
opm/porsol/common/SimulatorUtilities.hpp
opm/porsol/common/setupBoundaryConditions.hpp
opm/porsol/common/setupGridAndProps.hpp
opm/porsol/euler/EulerUpstreamImplicit_impl.hpp
opm/porsol/euler/EulerUpstream_impl.hpp
opm/porsol/euler/ImplicitCapillarity_impl.hpp
opm/porsol/mimetic/IncompFlowSolverHybrid.hpp
opm/upscaling/SteadyStateUpscalerImplicit_impl.hpp
opm/upscaling/SteadyStateUpscalerManagerImplicit.hpp
opm/upscaling/UpscalerBase_impl.hpp
opm/upscaling/initCPGrid.cpp

Preparatory work for removing sstream usage in OPM_THROW.

Remove sstream use in exception handling

---

CMakeLists.txt

unmaintained for 10 years with no complainers. let's send this to the eternal fields

remove stale static benchmark target

---

opm/upscaling/writeECLData.cpp

Downstream of https://github.com/OPM/opm-common/pull/3837

adjust to data::CellData change

---

opm/porsol/common/setupGridAndProps.hpp
opm/upscaling/initCPGrid.cpp

Downstream of https://github.com/OPM/opm-grid/pull/730

Remove support for legacy file format.

---

opm/porsol/common/Matrix.hpp
opm/porsol/mimetic/MimeticIPAnisoRelpermEvaluator.hpp
opm/porsol/mimetic/MimeticIPEvaluator.hpp

Mark comparison operator const and avoid arithmetics using enums

---

opm/core/transport/implicit/ImplicitAssembly.hpp
opm/core/transport/implicit/SinglePointUpwindTwoPhase.hpp
opm/porsol/euler/EulerUpstreamImplicit_impl.hpp

This is a draft PR to iron out warnings from the [pull request PR 818 in opm-grid](https://github.com/OPM/opm-grid/pull/818)

Converting size type of unstructured grid to unsigned int
