TestUpscalingBinaries.cmake
This change catches up to removal of trailing slash character in the `RESULT_PATH` variable in commit 16e06b1 (PR #147).
=> Adapt to RESULT_PATH losing trailing slash

examples/upscale_relperm.cpp
In the case of both phases being upscaled, only one of the tensors were sent,
i.e. the send-buffer was 3 doubles short. This causes program output to always
be wrong in the MPI version.
=> Makes MPI_Send use the correct buffer size.

opm/upscaling/RelPermUtils.cpp
Got a build error that seemed to be related to a missing include (see https://ci.opm-project.org/job/opm-upscaling-install/723/console)
=> Added cfloat include, build failed on some systems

opm/upscaling/ParserAdditions.hpp
This feels more natural and is also compatible with
https://github.com/OPM/opm-parser/pull/691
=> ParserAdditions passes json object, not keyword

opm/porsol/blackoil/fluid/BlackoilPVT.cpp, opm/porsol/blackoil/fluid/FluidMatrixInteractionBlackoil.hpp
The return type of `EclipseState::getTableManager()` changed from
```C++
std::shared_ptr<const TableManager>
```
to
```C++
const TableManager&
```
in commit OPM/opm-parser@4d4be1d (PR OPM/opm-parser#751).  Update callers accordingly.
=> Chase EclipseState::getTableManager() Return Type Update

debian/control, debian/rules, redhat/opm-upscaling.spec
- redhat: deal with new / renamed upstream modules and only use boost 1.48 on rhel6 since rhel7 supplies a newer boost by default.
debian: deal with new / renamed upstream modules, package with MPI and add related dependencies.
this has been tested with https://github.com/OPM/opm-upscaling/pull/182
@atgeirr please hit the green if there are no objections.
=> Updates for 16.04 packaging

debian/rules, tests/common/test_gravitypressure.cpp
In the interest of getting rc1 out the door, I pushed packages with these fixes in them.
The packaging fix was just something I forgot in opm-upscaling and had in the rest of the modules.
As for the second fix I paste the commit message;
> fixed: instance a MPI helper in gravity pressure test
>    the #undef HAVE_MPI trick does not work because we are linking
>    against MPI code already compiled in a library.
=> Fix mpi in gravity pressure test

tests/compareUpscaling.cpp
This PR is an extremely minor fixup (3 lines diff) for error messages when tests fail to find some file.  Previously, the error message was
```
For filename: <some_file_name>
```
Now we output the filename of the file that fails to be opened:
```
Could not open file <some_file_name>
```
=> Improved error message on file not found error

opm/elasticity/elasticity_preconditioners.hpp
It is my understanding that the macro `static_assert` has signature `(bool, str)`.  This PR is a one-line fix of the use of `static_assert` in the event that the user does not have UMFPACK nor SuperLU.
The full patch is:
```diff
-static_assert("Enable either SuperLU or UMFPACK");
+static_assert(false, "Enable either SuperLU or UMFPACK");
```
See also [Static assertion at cppreference](http://en.cppreference.com/w/cpp/language/static_assert).
=> usage of static_assert

opm/upscaling/SteadyStateUpscalerImplicit_impl.hpp
Was used from Compat.hpp that was moved out of opm-core.
This is a workaround and not an ideal solution, but it should restore a working master.
=> Duplicate destripe() utility.

opm/upscaling/CornerpointChopper.hpp
Commit OPM/opm-parser@c959055 (PR OPM/opm-parser#950) changed the syntax for constructing `DeckItem`s.  Update the `CornerpointChopper` accordingly.
=> Bring CornerpointChopper Up-To-Date With DeckItem API

CMakeLists_files.cmake, opm/upscaling/SteadyStateUpscalerImplicit_impl.hpp, opm/upscaling/writeECLData.cpp, opm/upscaling/writeECLData.hpp
The file `writeECLData` was maintained in opm-output only for the sake of opm-upscaling. If this PR is merged we will subsequently merge this: https://github.com/OPM/opm-output/pull/131
A better solution for opm-upscaling would be to use the proper EclipseWriter from opm-output, but that is *slightly* more work than this pure moving of files.
**Update:** Please hold - seems the deprecated `writeECLData` is also used in some the less maintained parts of opm-simulators.
=> Added file writeECLData from opm-output.

opm/upscaling/writeECLData.cpp
See: https://github.com/OPM/opm-output/pull/176
Any reason this is not using opm-output?
=> Adapt to change in ert data type.

opm/porsol/common/setupGridAndProps.hpp, opm/upscaling/UpscalerBase_impl.hpp
This fixes a bug related to upscaling grids that are not "shoe-box" shaped, for such cases the grid must be z-clipped if either linear or periodic boundary conditions are to be used for the upscaling. (For the linear bc case this could be relaxed but that would require a bit of rewriting.) The fix includes:
- For the setup path used by the single-phase upscaling code: now also set clip_z to true for Linear bcs.
- For the setup path used by the steady-state upscaling code: set clip_z to true for Linear *and* Periodic bcs (note that this path did not even have this logic present for Periodic bcs before).
I intend to self-merge this when green.
=> Require z-clipping for both linear and periodic bc types.

CMakeLists.txt, CMakeLists_files.cmake, dune.module, examples/upscale_elasticity.cpp, opm/elasticity/boundarygrid.hh, opm/elasticity/elasticity_preconditioners.hpp, opm/elasticity/elasticity_upscale_impl.hpp, opm/porsol/common/GridInterfaceEuler.hpp, opm/porsol/mimetic/IncompFlowSolverHybrid.hpp
OPM (in particular simulators) now depends on dune 2.4 for proper behavior. This makes this requirement hard.
=> Require Dune 2.4

dune.module
since the dependency order of opm-grid and opm-core has been reversed, opm-grid does not imply opm-core anymore but vice-versa.
for opm-parser, it is IMO good style to specify all dependencies explicitly.
please merge this together with OPM/opm-common#261 .
=> dune.module: add opm-parser and opm-core to the dependencies

examples/upscale_relperm.cpp
resulted in unexpected file names if path held a dot.
In particular this was seen on jenkins, where the dune 2.4 build has a dot in the configuration name. We ended up with files named 'dune-2-X.SWOF' et al on top of workspace.
=> fixed: look for last dot, not first

opm/core/transport/implicit/TransportSolverTwophaseImplicit.cpp, opm/upscaling/SteadyStateUpscalerImplicit_impl.hpp
The waterSatToBothSat() function is just a copy of toBothSat(), I deem it sufficiently trivial that it's ok to duplicate.
=> Avoid depending on miscUtilities.hpp from opm-core.

dune.module
this is now required because opm-core is gone and thus opm-output is no longer implicitly available.
=> dune.module: advertise opm-output as a dependency

compareUpscaling.cmake
to aid the use of a super project for opm, see https://github.com/OPM/opm-common/pull/321
=> changed: use PROJECT_BINARY_DIR instead of CMAKE_BINARY_DIR

benchmarks/upscale_relperm_benchmark.cpp
besides the new way of doing things being better IMO, `Unused.hpp` should not be used by this module anymore.
=> better fix for squelching unused variable

CMakeLists_files.cmake, compareUpscaling.cmake, examples/cpchop.cpp, opm/upscaling/CornerpointChopper.hpp, tests/input_data/reference_solutions/cpchop_PeriodicTilted.txt
Two problems:
- non-empty interval for the random number generator for z starting coordinates
- problematic cc for the Deck class. workaround by moving to initializer list so move semantics are used.
=> Fix issue 259

tests/common/test_gravitypressure.cpp
=> remove unused variable

examples/upscale_elasticity.cpp, opm/porsol/common/setupGridAndProps.hpp, opm/upscaling/initCPGrid.cpp
... instead of a reference This is needed as we only want to read the
full deck and construct the EclipseGrid only on the master process
with rank 0. Hence all other ranks will pass a nullptr to this
function. This will be possible with this move from a reference to a
pointer.
downstream of PR OPM/opm-grid#433
=> Pass a pointer to the EclipseGrid to CpGrid::processEclipseGrid.

opm/upscaling/RelPermUtils.cpp
Preparation for removing the large keyword header.
=> Use specific headers S.hpp and P.hpp

opm/upscaling/UpscalerBase_impl.hpp
This turned out to be unrelated to #308, but was discovered during testing for that fix.
The bug is pretty serious, and could have bitten anytime. On the plus side, uninitialized non-zero data are likely to be much larger than any sensible gravity acceleration, so it was more likely to cause failures (as for me) than wrong results.
=> Initialize gravity_ member.

opm/upscaling/SteadyStateUpscalerImplicit_impl.hpp
I know this is oppsite of the current remove boost efforts. The boost header must have been included transitively in some way previously. With these PR's the transitive include failes
https://github.com/OPM/opm-common/pull/1477
https://github.com/OPM/opm-simulators/pull/2343
=> Add explicit include of boost/date_time dependency

debian/rules
accidentially discovered that we build without openmp, because -DUSE_OPENMP=0 is broken now (if opm-common was built with openmp).
Backport.
=> build packages with OpenMP enabled

opm/upscaling/writeECLData.hpp
Needed to bring a declaration of 'time_t' into scope.
Submitted by: Edscott Wilson Garcia
Fixes #322
=> Bring in Missing <time.h> Header

redhat/opm-upscaling.spec
- use system level boost now that RHEL6 is dead
=> fix redhat packaging

opm/elasticity/boundarygrid.hh, opm/elasticity/elasticity_upscale_impl.hpp, opm/porsol/common/GridInterfaceEuler.hpp
Drop removed second template parameter from MultipleCodimMultipleGeomTypeMapper (there is a default since 2.6
and now the second parameter is gone). 
Also fixes some other deprecation warnings about the deprecated LeafMultipleCodimMultipleGeomTypeMapper
=> Support Dune 2.8 version of MultipleCodimMultipleGeomTypeMapper

redhat/opm-upscaling.spec
- add parameter for which toolset to use
- build against openmpi3
- add boolean flags for the different mpi builds (mostly for testing)
- add parameter for appending extra token to package names.
this can be used for allowing multiple versions to be installed on the
same system.
=> update redhat packaging

CMakeLists_files.cmake
forgotten in 127850e3e79528156026ef23eef5dce353967ff0
=> remove stale reference from CMakeLists_files.txt

CMakeLists_files.cmake
forgotten in 127850e3e79528156026ef23eef5dce353967ff0
backport of PR #354
=> [backport] remove stale reference from CMakeLists_files.txt

CMakeLists_files.cmake
It does not seem to be useful.
=> Do not install steadystate_test_implicit.

tests/run-compareUpscaling.sh
if not blas potentially eats all the cores which significantly slows down execution on the small test models
=> changed: run tests using a single thread

CMakeLists.txt
minimum version should come before project statement
=> quell CMake warning

benchmarks/upscale_relperm_benchmark.cpp
=> drop use of deprecated std::bind1first

CMakeLists.txt, opm/elasticity/elasticity_preconditioners.hpp, opm/elasticity/elasticity_upscale_impl.hpp
Following PR OPM/opm-common#4202 (commit OPM/opm-common@757a9538b) there is only `HAVE_SUITESPARSE_UMFPACK`.
=> Chase Removal of HAVE_UMFPACK Preprocessor Symbol

compareUpscaling.cmake, opm/upscaling/UpscalerBase_impl.hpp, tests/run-compareUpscaling.sh
we need the grid on all processes, so pass MPI_COMM_SELF communicator to the grid instance
This probably broke a long time ago.
=> fixed: parallel execution of relperm upscaling
